# Generated by Django 4.1.4 on 2022-12-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
