# Generated by Django 4.1.4 on 2022-12-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='content',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=996999067807),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
